spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  #    properties:
  #      hibernate:
  #        show_sql: true
  #        format_sql: true
  #        use_sql_comments: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    name: ${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
#logging:
#  level:
#    org.hibernate:
#      type:
#        descriptor:
#          sql: trace
custom-properties:
  jwt.secret-key: ${JWT_SECRET_KEY}
